
backend: Inject
undo_backspace: false

# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  
  - trigger: "::@l"
    replace: "logic@newbaselogic.com"

  - trigger: "::date"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%F"

  - trigger: "::now"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%+"